#baseURL = "https://knative.dev"
baseURL = "https://davidhadas.github.io/knwebsite/"
title = "Knative"

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]


# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableBrowserError = true

disableKinds = ["taxonomy", "taxonomyTerm"]

ignoreFiles = [ "(?:^|/)OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$", "content/en/docs/doc-contributor-tools" ]

timeout = "180s"

# Highlighting config.
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true
[caches]
 [caches.assets]
  dir = ":cacheDir/_gen"
  maxAge = -1
 [caches.getcsv]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.getjson]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.images]
  dir = ":cacheDir/_images"
  maxAge = -1
 [caches.modules]
  dir = ":cacheDir/modules"
  maxAge = -1

[markup]
 [markup.goldmark]
   [markup.goldmark.extensions]
     definitionList = true
     table = true
     typographer = false
   [markup.goldmark.parser]
     attribute = true
     autoHeadingID = true
     autoHeadingIDType = "blackfriday"
   [markup.goldmark.renderer]
     unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[sitemap]
  filename = "sitemap.xml"
  priority = 0.75

# Be explicit about the output formats. We (currently) only want an RSS feed for the home page.
[outputs]
home = [ "HTML", "RSS", "HEADERS" ]
page = [ "HTML"]
section = [ "HTML", "print" ]

# Add a "text/netlify" media type for auto-generating the _headers file
[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats]
[outputFormats.RSS]
baseName = "feed"

# _headers file output (uses the template at layouts/index.headers)
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Fake ID in support of [params.ui.feedback]. The real GA ID is set in the Netlify config.
id = "UA-00000000-0"

[params]
copyright_k8s = "The Knative Authors"
copyright_linux = "Copyright © 2022 The Linux Foundation ®."

# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Versions"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 02, 2006 at 3:04 PM PST"

description = "Kubernetes made simpler and safer"
showedit = true

latest = "v1.25"

fullversion = "v1.25.0"
version = "v1.25"
githubbranch = "main"
docsbranch = "main"
deprecated = false
currentUrl = "https://knative.dev/docs"
nextUrl = "https://knative.dev/"

# See codenew shortcode
githubWebsiteRaw = "raw.githubusercontent.com/knative/website"

# GitHub repository link for editing a page and opening issues.
github_repo = "https://github.com/knative/website"

# Searching
k8s_search = true

# The following search parameters are specific to Docsy's implementation. Knative implementes its own search-related partials and scripts.

# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Official CVE feed bucket URL
cveFeedBucket = "https://storage.googleapis.com/k8s-cve-feed/official-cve-feed.json"

[params.pushAssets]
css = [
  "callouts",
  "styles"
]
js = [
  "script"
]


[[params.versions]]
fullversion = "v1.7"
version = "v1.7"
githubbranch = "v1.7"
docsbranch = "main"
url = "https://knative.dev"

[[params.versions]]
fullversion = "v1.6"
version = "v1.6"
githubbranch = "v1.6"
docsbranch = "release-1.6"
url = "https://knative.dev/v1.6-docs/"


[[params.versions]]
fullversion = "v1.5"
version = "v1.5"
githubbranch = "v1.5"
docsbranch = "release-1.5"
url = "https://knative.dev/v1.5-docs/"


[[params.versions]]
fullversion = "v1.4"
version = "v1.4"
githubbranch = "v1.4"
docsbranch = "release-1.4"
url = "https://knative.dev/v1.4-docs/"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Show expand/collapse icon for sidebar sections.
sidebar_menu_foldable = true
# https://github.com/gohugoio/hugo/issues/8918#issuecomment-903314696
sidebar_cache_limit = 1
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.

[[params.links.user]]
	name = "Twitter"
	url = "https://twitter.com/KnativeProject"
	icon = "fab fa-twitter"
	desc = "Follow us on Twitter to get the latest news!"


[[params.links.user]]
	name = "Getting Started"
	url = "https://knative.dev/docs/getting-started/"
	icon = "fa-regular fa-graduation-cap"
	desc = "Getting started with Knative!"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/knative/"
	icon = "fab fa-github"
	desc = "Development takes place here!"

[[params.links.developer]]
	name = "Slack"
	url = "https://slack.knative.dev"
	icon = "fab fa-slack"
	desc = "Chat with other project developers"

[[params.links.developer]]
	name = "Contribute"
	url = "https://knative.dev/docs/contributing/contributing/"
	icon = "fas fa-edit"
	desc = "Contribute to Knative"

[[params.links.developer]]
	name = "Stack Overflow"
	url = "https://stackoverflow.com/questions/tagged/knative"
	icon = "fab fa-stack-overflow"
	desc = "Practical questions and curated answers"

# Language definitions.

[languages]
[languages.en]
title = "Knative"
description = "Kubernetes made simpler and safer"
languageName = "English"
# Weight used for sorting.
weight = 1
languagedirection = "ltr"


[[menu.main]]
name = "Documentation"
weight = 20
url = "https://knative.dev/docs/"

[[menu.main]]
name = "Tutorial"
weight = 40
url = "https://knative.dev/docs/getting-started/"

[[menu.main]]
name = "CLI"
weight = 60
url = "https://knative.dev/docs/client/"

[[menu.main]]
name = "Community"
weight = 70
url = "https://knative.dev/docs/contributing/"

[[menu.main]]
name = "Testimonials"
weight = 80
url = "https://knative.dev/docs/about/testimonials/"
